CREATE SCHEMA `db1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

 CREATE  TABLE `db1`.`config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );
  
  
CREATE SCHEMA `db2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

 CREATE  TABLE `db2`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );
